### ISSUE TITLE
TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'

### ISSUE THREAD

**Issue by Andie-Squirrel** [etched-ai/open-oasis#15]
On running `python generate.py` in the main directory for the first time, I was met with this traceback:

`Traceback (most recent call last):
  File "A:\Ai Overflow\Games\Oasis by Decart\open-oasis\generate.py", line 6, in <module>
    from dit import DiT_models
  File "A:\Ai Overflow\Games\Oasis by Decart\open-oasis\dit.py", line 12, in <module>
    from embeddings import Timesteps, TimestepEmbedding
  File "A:\Ai Overflow\Games\Oasis by Decart\open-oasis\embeddings.py", line 11, in <module>
    from diffusers.models.embeddings import TimestepEmbedding
  File "C:\Program Files\Python310\lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Program Files\Python310\lib\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import DIFFUSERS_CACHE, HUGGINGFACE_CO_RESOLVE_ENDPOINT, DummyObject, deprecate, logging
  File "C:\Program Files\Python310\lib\site-packages\diffusers\utils\__init__.py", line 22, in <module>
    from .import_utils import (
  File "C:\Program Files\Python310\lib\site-packages\diffusers\utils\import_utils.py", line 207, in <module>
    if torch.__version__ < version.Version("1.12"):
TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'`

I am running Windows 10 and using Python 3.10, if that's relevant at all. I wasn't sure this was going to work locally for me anyways at this point, but any help is nonetheless greatly appreciated!

**Comment by questynesty** [comment]
I have the same issue

**Comment by PoliteApps** [comment]
OK, I tried it out with Python 3.11 and it worked just fine. Maybe for some reason the authors forgot to specify the python version. Anyhow, I am using a part of an A100 GPU with 20 GB and Linux, for reference...
