### ISSUE TITLE
Please help me solve this problem，Thanks

### ISSUE THREAD

**Issue by s0x401** [etched-ai/open-oasis#41]
Traceback (most recent call last):
  File "D:\AI\open-oasis\generate.py", line 199, in <module>
    main(args)
  File "D:\AI\open-oasis\generate.py", line 133, in main
    write_video(args.output_path, x[0].cpu(), fps=args.fps)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\io\video.py", line 140, in write_video
    frame.pict_type = "NONE"
    ^^^^^^^^^^^^^^^
  File "av\\video\\frame.pyx", line 193, in av.video.frame.VideoFrame.pict_type.__set__
TypeError: an integer is required
![b6051460-4409-4995-b62c-5264e7b89c83](https://github.com/user-attachments/assets/4d121173-910b-4ed8-8b40-d2af5f732ab9)

**Comment by seonjunn** [comment]
For those who encounter this error, you can fix this by pinning torchvision version to 0.23.
i.e.,
```
pip install torchvision==0.23
```
Check [[this commit](https://github.com/pytorch/vision/commit/6279faa88a3fe7de49bf58284d31e3941b768522)] if you want more detail.
